version: '3.4'

services:
  audioplayer:
    image: fsazanavets/signalr-audio-player:linux
    volumes:
     - /usr/bin/aplay:/usr/bin/aplay
    restart: unless-stopped
    devices:
     - /dev/snd
    environment:
     - DEVICE_IDENTIFIER: '12345'
     - AREA_NAME: 'North Wing'
     - GATE_NUMBER: '1'
     - HUB_URL: 'http://localhost:57100/devicesHub'